### ISSUE TITLE
LuaException: c# exception:XLua.LuaException: error loading module bundle_1.30.001 from CustomLoader, bundle_1.30.001:1: unexpected symbol near '<'

### ISSUE THREAD

**Issue by SweetMei25** [CragonGame/CasinosClient#14]
我希望你解决我的问题。

I want you to solve my problem.

**Comment by xiaolige945** [comment]
是在mac系统上面出现的问题吗？mac系统有几天没有运行测试了，win上面是可以直接运行的

**Comment by SweetMei25** [comment]
我在Windows上运行它。 我没有在mac上运行它。

**Comment by SweetMei25** [comment]
当我第一次使用Unity 2018.2.20f1打开项目时，会显示此错误
我无法解决这些错误，因此我对它们进行了评论。
![1](https://user-images.githubusercontent.com/41826639/50724351-8d5ec480-111e-11e9-836f-c0d7d8544769.png)

**Comment by xiaolige945** [comment]
试试删除XLua.Gen目录，然后点击unity3d菜单项Xlua->Generate Code重新生成该目录

**Comment by SweetMei25** [comment]
这种无休止的错误正在发生......
:(   请告诉我如何解决。

![2](https://user-images.githubusercontent.com/41826639/50728409-bea9b580-115b-11e9-9cd4-a22ccb1b3bad.png)

**Comment by xiaolige945** [comment]
Unity切换平台到Android运行即可，不支持PC&Mac

**Comment by SweetMei25** [comment]
非常感谢，我将尝试Android平台，我会告诉你。

**Comment by SweetMei25** [comment]
它也不适用于Android设备！  😢 
另外，有没有办法在Unity Editor上进行测试？

**Comment by SweetMei25** [comment]
![image](https://user-images.githubusercontent.com/41826639/50736143-260f4600-11ec-11e9-9f9a-ad04f54fc05b.png)

**Comment by xiaolige945** [comment]
1. 模拟器没有经过充分测试，因为模拟器容易开多号打伙牌；
2. 目前应该是检测了本机国家和语言，加载了英文语言包，英文语言包未经过充分测试，可以手动切换到中文语言
![1](https://user-images.githubusercontent.com/3381204/50736647-f7e53280-11fa-11e9-8fcb-8154a195b7c4.png)

**Comment by xiaolige945** [comment]
手动切换到该枚举值：SystemLanguage.ChineseSimplified
![xosuv2abt 47yt7 nuy2q 5](https://user-images.githubusercontent.com/3381204/50736679-57434280-11fb-11e9-8839-24ef46603ac7.png)

**Comment by xiaolige945** [comment]
目前正处于的界面是准备到阿里云上海区Oss Bucket中加载lua文件，可以在浏览器中手动输入该url：
https://cragon-king-oss.cragon.cn/Common/1.00.000/Lua/Context.txt
看看打开是否顺畅，确认下是否有网络问题。

**Comment by SweetMei25** [comment]
我用简体中文更改了语言。
我修改的是：
![image](https://user-images.githubusercontent.com/41826639/50738442-94610200-1206-11e9-90c8-c145ee7384e4.png)
结果是：
![image](https://user-images.githubusercontent.com/41826639/50738448-a478e180-1206-11e9-8dbd-50e1102809cd.png)
仍然无法继续加载。
我输入了你的网址:
https://cragon-king-oss.cragon.cn/Common/1.00.000/Lua/Context.txt
![image](https://user-images.githubusercontent.com/41826639/50738465-ce320880-1206-11e9-8fc0-47af593bc5ae.png)

我很困惑，我现在该怎么办？ 

我非常感谢您的出色服务，但我也想解决这个问题。
我期待着您的回音
谢谢

**Comment by SweetMei25** [comment]
精彩！
我再次跑，它工作正常......！
👍

**Comment by SweetMei25** [comment]
啊，我明白了
所以这是语言问题

**Comment by xiaolige945** [comment]
不错！没有预先准备测试账号，可以自己使用手机号加验证码自行注册账号^^

**Comment by xiaolige945** [comment]
通过该界面注册手机账号，记得选择准确的国家码
![c hl8 al03mwnzp0x8wr](https://user-images.githubusercontent.com/3381204/50739689-9f279100-121e-11e9-9c33-d96891d99795.png)

**Comment by SweetMei25** [comment]
因为它不起作用
我输入了正确的验证码，但它无效。
😢

**Comment by SweetMei25** [comment]
[上海螭龙网络科技有限公司]亲，你的果派德州验证码是5334，1分钟内有效
--

**Comment by SweetMei25** [comment]
我认为这已经有访客登录功能。
是否可以以访客身份登录？

**Comment by xiaolige945** [comment]
游客访问和微信登录功能都已在服务端接口层面屏蔽了，后续做全球化版本，手机是通用账号，微信，facebook之类第三方登录模块会根据当前地区动态加载后使用。手机注册应该是没有问题的，我刚刚看了服务端日志，发现你调用是reset password，而不是register，估计是点击了错误的中文注册按钮。

**Comment by xiaolige945** [comment]
按图中标示的步骤注册：
![1s27i elg7 xgerkv9wie m](https://user-images.githubusercontent.com/3381204/50740169-8cfd2100-1225-11e9-8d57-21f5ec532f5a.png)
![cfwvxf77 5npd uzgzzg3t7](https://user-images.githubusercontent.com/3381204/50740170-8ff81180-1225-11e9-885f-24ffa6cb237a.png)

**Comment by SweetMei25** [comment]
是的它正在发挥作用
谢谢。

**Comment by SweetMei25** [comment]
主德州扑克引擎在哪里？
引擎是否位于客户端或服务器端？

**Comment by xiaolige945** [comment]
两大主玩法德州普通场和赛事场，分为Client和Servier两个模块，Client主要负责界面呈现，Server主要负责流程数据等业务逻辑处理。Server端是商业闭源的，Client端的主玩法lua代码在View.DesktopTexas目录中。

**Comment by SweetMei25** [comment]
你好
你能和我分享服务器端代码吗？

**Comment by SweetMei25** [comment]
另外，如果您同意，我想与您的团队合作。
