### ISSUE TITLE
XLua

### ISSUE THREAD

**Issue by vijitendra** [CragonGame/CasinosClient#26]
![1](https://user-images.githubusercontent.com/19763107/57065485-3097a300-6ce7-11e9-9019-66f676157274.PNG)
Unable to read header from archive file: C:/Users/JMVAS/AppData/LocalLow/jmvas/game/Launch/Android/loadingmarry.ab
System.Reflection.MethodBase:Invoke(Object, Object[])
ILRuntime.CLR.Method.CLRMethod:Invoke(ILIntepreter, StackObject*, IList`1, Boolean) (at Assets/Lib.ILRuntime/ILRuntime/CLR/Method/CLRMethod.cs:316)
ILRuntime.Runtime.Intepreter.ILIntepreter:Execute(ILMethod, StackObject*, Boolean&) (at Assets/Lib.ILRuntime/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:1797)
ILRuntime.Runtime.Intepreter.ILIntepreter:Execute(ILMethod, StackObject*, Boolean&) (at Assets/Lib.ILRuntime/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:1757)
ILRuntime.Runtime.Intepreter.ILIntepreter:Execute(ILMethod, StackObject*, Boolean&) (at Assets/Lib.ILRuntime/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:1757)
ILRuntime.Runtime.Intepreter.ILIntepreter:Execute(ILMethod, StackObject*, Boolean&) (at Assets/Lib.ILRuntime/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:1757)
ILRuntime.Runtime.Intepreter.ILIntepreter:Execute(ILMethod, StackObject*, Boolean&) (at Assets/Lib.ILRuntime/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:1757)
ILRuntime.Runtime.Intepreter.ILIntepreter:Execute(ILMethod, StackObject*, Boolean&) (at Assets/Lib.ILRuntime/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:1757)
ILRuntime.Runtime.Intepreter.ILIntepreter:Run(ILMethod, Object, Object[]) (at Assets/Lib.ILRuntime/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:96)
ILRuntime.Runtime.Enviorment.AppDomain:Invoke(IMethod, Object, Object[]) (at Assets/Lib.ILRuntime/ILRuntime/Runtime/Enviorment/AppDomain.cs:1086)
ILRuntime.Runtime.Enviorment.AppDomain:Invoke(String, String, Object, Object[]) (at Assets/Lib.ILRuntime/ILRuntime/Runtime/Enviorment/AppDomain.cs:989)
Casinos.MbLaunch:_launch() (at Assets/Script/Main/MbLaunch.cs:389)
Casinos.MbLaunch:Start() (at Assets/Script/Main/MbLaunch.cs:79)

**Comment by xiaolige945** [comment]
这个错误是在master分支中报出的，master分支是ILRuntime重构半成品，无法运行；Branch_1.1.00
分支中的是xLua版本，可以在Android中运行成功。

**Comment by vijitendra** [comment]
Dear Sir,
How can register and login in game,
I am trying to get Phone code but I am facing problem

Android Game Developer
Vijitendra kumar

Atechnos


<https://www.avast.com/en-in/recommend?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=default3&tag=93380f80-3a94-40f5-81cc-bb1f433a54e0>
I’m
protected online with Avast Free Antivirus. Get it here — it’s free forever.
<https://www.avast.com/en-in/recommend?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=default3&tag=93380f80-3a94-40f5-81cc-bb1f433a54e0>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by vijitendra** [comment]
亲爱的先生，
如何在游戏中注册和登录，
我正在尝试获取电话代码，但我遇到了问题


Android Game Developer
Atechnos

**Comment by vijitendra** [comment]
Seeing Ucenter Unknown Error,

Android Game Developer
Atechnos


<https://www.avast.com/en-in/recommend?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=default3&tag=93380f80-3a94-40f5-81cc-bb1f433a54e0>
I’m
protected online with Avast Free Antivirus. Get it here — it’s free forever.
<https://www.avast.com/en-in/recommend?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=default3&tag=93380f80-3a94-40f5-81cc-bb1f433a54e0>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by xiaolige945** [comment]
返回UCenter Unknown Error， 是因为测试环境的UCenter服务器已经关闭了，暂时没有可用的服务器。过2周左右我们会重新部署测试环境的UCenter服务器！

**Comment by vijitendra** [comment]
Sir,
How can we signup, any other option.

Android Game Developer
Atechnos


<https://www.avast.com/en-in/recommend?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=default3&tag=93380f80-3a94-40f5-81cc-bb1f433a54e0>
I’m
protected online with Avast Free Antivirus. Get it here — it’s free forever.
<https://www.avast.com/en-in/recommend?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=default3&tag=93380f80-3a94-40f5-81cc-bb1f433a54e0>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by xiaolige945** [comment]
测试服务器关闭了就没法注册或登录游戏了，只有等待测试环境的重新部署或者自己写一套服务端。

**Comment by vijitendra** [comment]
NullReferenceException: Object reference not set to an instance of an
object.
ILRuntime.Runtime.Intepreter.ILIntepreter.Execute
(ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject*
esp, System.Boolean& unhandledException) (at
Assets/Lib.ILRuntime/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:1981)
Rethrow as ILRuntimeException: Object reference not set to an instance of
an object.
IL_0035: ldfld System.String Cs.VersionInfoRemote::BundleSelectPro
Cs.ControllerLaunch._onDownloadBundleCfg(String text)
F:/Casinos.Common/_Client/Controller/ControllerLaunch.cs:Line 140

Sir,
I am facing above issue when play game.

Thanks and Regards,
Vijitendra kumar

Android Game Developer
Atechnos
